UPDATE abilities SET CE = 2800 WHERE name = 'invincible';
UPDATE abilities SET recastTime = 120 WHERE name = 'warcry';
UPDATE abilities SET CE = 200 WHERE name = 'provoke';
UPDATE abilities SET recastTime = 180, isAOE = 1, VE = 50 WHERE name = 'chakra';
UPDATE abilities SET recastTime = 60 WHERE name = 'steal';
UPDATE abilities SET recastTime = 60 WHERE name = 'hide';
UPDATE abilities SET recastTime = 60 WHERE name = 'mug';
UPDATE abilities SET recastTime = 60, CE = 200 WHERE name = 'shield_bash';
UPDATE abilities SET recastTime = 300 WHERE name = 'holy_circle';
UPDATE abilities SET CE = 100 WHERE name = 'sentinel';
UPDATE abilities SET VE = 600 WHERE name = 'souleater';
UPDATE abilities SET recastTime = 300 WHERE name = 'arcane_circle';
UPDATE abilities SET VE = 600 WHERE name = 'last_resort';
UPDATE abilities SET recastTime = 60 WHERE name = 'shadowbind';
UPDATE abilities SET recastTime = 300 WHERE name = 'call_wyvern';
UPDATE abilities SET recastTime = 300 WHERE name = 'warding_circle';
UPDATE abilities SET recastTime = 300 WHERE name = 'ancient_circle';
UPDATE abilities SET recastTime = 60 WHERE name = 'jump';
UPDATE abilities SET recastTime = 120 WHERE name = 'high_jump';
UPDATE abilities SET recastTime = 300 WHERE name = 'divine_seal';
UPDATE abilities SET recastTime = 300 WHERE name = 'elemental_seal';
UPDATE abilities SET CE = 100, VE = 100 WHERE name = 'cover';
UPDATE abilities SET recastTime = 120 WHERE name = 'spirit_link';
UPDATE abilities SET recastTime = 120 WHERE name = 'chi_blast';
UPDATE abilities SET recastTime = 180 WHERE name = 'accomplice';
UPDATE abilities SET recastTime = 50 WHERE name = 'blood_pact_rage';
UPDATE abilities SET CE = 100 WHERE name = 'rampart';
UPDATE abilities SET recastTime = 45 WHERE abilityId between 97 and 122; -- Corsair Rolls
UPDATE abilities SET recastTime = 600 WHERE name = 'random_deal';
UPDATE abilities SET recastTime = 2400 WHERE name = 'overdrive';
UPDATE abilities SET recastTime = 120 WHERE name = 'shikikoyo';
UPDATE abilities SET recastTime = 50 WHERE name = 'blood_pact_ward';
UPDATE abilities SET recastTime = 2400 WHERE name = 'trance';
UPDATE abilities SET recastTime = 2400 WHERE name = 'tabula_rasa';
UPDATE abilities SET recastTime = 180 WHERE name = 'sekkanoki';
UPDATE abilities SET level = 75 WHERE name = 'impetus';
UPDATE abilities SET level = 75 WHERE name = 'conspirator';
UPDATE abilities SET level = 75 WHERE name = 'palisade';
UPDATE abilities SET level = 75 WHERE name = 'marcato';
UPDATE abilities SET level = 75 WHERE name = 'decoy_shot';
UPDATE abilities SET level = 75 WHERE name = 'crooked_cards';
UPDATE abilities SET recastTime = 120 WHERE name = 'unlimited_shot';
UPDATE abilities SET recastTime = 220 WHERE name = 'sharpshot';

UPDATE abilities SET content_tag = NULL;